### ISSUE TITLE
Feat: 성장 기록 페이지 수정 삭제 구현

### ISSUE THREAD

**Issue by mun-jihye** [Donggrina/Frontend#127]
## Description
성장 기록 메인 화면 수정 삭제 구현

## Todo
- [ ] 성장 기록 메인 화면 리스트 수정 시 기존 데이터 불러오기
- [ ] 수정 완료 시 모달
- [ ] 성장 기록 리트스 삭제 구현
- [ ] 삭제 선택 했을 경우 경고 모달

## ETC
기타 사항
