### ISSUE TITLE
Feat: modal 공통 컴포넌트

### ISSUE THREAD

**Issue by forestream** [Donggrina/Frontend#23]
## Description
공용 모달 컴포넌트 제작

## Todo
- [x] 모달 ui 구현
- [x] 모달별 버튼을 프롭으로 받도록 구현
- [x] createPortal 용 html 요소 생성
- [x] 백그라운드 클릭 시 모달 닫히는 코드 작성

**Comment by mun-jihye** [comment]
https://github.com/TheJulge/Frontend/issues/1#issue-2241227880
한빈님! 해당 링크 확인해보시고 할 일을 좀더 구체적으로 작성해주실수 있을까욥?
