### ISSUE TITLE
Feat: input 공통 컴포넌트 포메팅 구현하기

### ISSUE THREAD

**Issue by mun-jihye** [Donggrina/Frontend#48]
## Description
input 공통 컴포넌트 포메팅 구현하기

## Todo

- [x] 컴파운드 패턴 적용
- [x] 날짜 입력받는 인풋 구현
- [x] 몸무게 입력 인풋
- [x] 유효성 검사 정규식 구현
- [x] 제출 버튼 클릭시 콘솔에 입력값 출력해보기
- [x] 타입 공통화

## ETC
기타 사항
