### ISSUE TITLE
Feat: select component 구현

### ISSUE THREAD

**Issue by mun-jihye** [Donggrina/Frontend#55]
## Description
공통 컴포넌트로 select component 구현

## Todo
- [x] 디자인 잡기
- [x] 외부를 클릭했을 경우 닫히도록 구현
- [x] 위, 아래 버튼을 클릭했을 경우 닫히도록 구현
- [x] select 내부 값은 사용자가 추가할 수 있도록 구현

## ETC
기타 사항
