### ISSUE TITLE
Refactor: Label 컴포넌트 분리

### ISSUE THREAD

**Issue by mun-jihye** [Donggrina/Frontend#67]
## Description
인풋 컴포넌트와 라벨 컴포넌트를 분리

## Todo
- [x] 인풋 컴포넌트와 라벨 컴포넌트를 분리
- [x] 라벨 컴포넌트 디자인 수정
- [x] 인풋 전체 컴포넌트 디자인 수정

## ETC
기타 사항
