### ISSUE TITLE
Feat: 성장기록 메인 화면 구현

### ISSUE THREAD

**Issue by mun-jihye** [Donggrina/Frontend#70]
## Description
성장 기록 메인 화면 구현 및 api 연동

## Todo
- [x] 캘린더 불러오기
- [x] 성장기록 리스트 컴포넌트 디자인
- [x] 성장기록 리스트 컴포넌트 api 연동
- [x] 성장기록 메인 화면 ui 구현
- [x] 성장기록 메인 화면 api 연동

## ETC
기타 사항
