### ISSUE TITLE
Feat: Family UI 작업하기.

### ISSUE THREAD

**Issue by D5ng** [Donggrina/Frontend#79]
## Description
Family UI 작업하기.
어떤 작업에 관한 이슈 인가요?

## Todo
- [x] Family 날짜 출력하기.
- [x] 다이어리 영역 만들기.
- [x] 성장기록 영역 만들기.
- [x] 일정기록 영역 만들기.

## ETC
기타 사항
