### ISSUE TITLE
Feat: 성장기록 추가 페이지 구현

### ISSUE THREAD

**Issue by mun-jihye** [Donggrina/Frontend#82]
## Description
성장기록 추가 페이지 ui 및 데이터 연동

## Todo
- [x] 성장기록 추가 페이지 ui 구현
    - [x] 사료
    - [x] 간식
    - [x] 이상증상
    - [x] 병원
- [x] 데이터 post 요청 
- [x] 작성 도중 사용자가 페이지 나갈 시에 모달 처리

## ETC
기타 사항
