### ISSUE TITLE
Feat: 캘린더 전역 상태 관리

### ISSUE THREAD

**Issue by D5ng** [Donggrina/Frontend#97]
## Description
캘린더 zustand를 사용해 전역 상태 관리하기.
어떤 작업에 관한 이슈 인가요?

## Todo
- [x] zustand package install
- [x] 전역상태 셀렉터 설정하기.
- [x] 캘린더 날짜관련 전역상태 추가

## ETC
기타 사항
